-- Commune backup 2026-07-08T16:45:30.776Z
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (1,'Alger-Centre','الجزائر الوسطى',36.7372,3.0875,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (2,'Sidi M''Hamed','سيدي امحمد',36.75,3.0933,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (3,'El Madania','المدنية',36.7411,3.0742,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (4,'Casbah','القصبة',36.785,3.06,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (5,'Hussein Dey','حسين داي',36.735,3.117,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (6,'Oued Koriche','وادي قريش',36.775,3.035,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (7,'Bab El Oued','باب الوادي',36.79,3.05,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (8,'Bologhine','بولوغين',36.8,3.03,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (9,'Bir Mourad Raïs','بئر مراد رايس',36.72,3.06,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (10,'Hydra','حيدرة',36.745,3.02,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (11,'El Biar','الأبيار',36.755,3.015,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (12,'El Mouradia','المرادية',36.73,3.05,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (13,'Birkhradem','بئر خادم',36.705,3.05,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (14,'Bouzaréah','بوزريعة',36.78,3,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (15,'El Achour','الأشور',36.735,2.985,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (16,'Dely Ibrahim','دالي إبراهيم',36.76,2.98,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (17,'Ben Aknoun','بن عكنون',36.76,2.99,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (18,'Beni Messous','بني مسوس',36.775,2.97,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (19,'Rahmania','الرحمانية',36.8,2.95,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (20,'Souidania','السويدانية',36.765,2.93,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (21,'Chéraga','الشراقة',36.765,2.96,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (22,'Aïn Benian','عين البنيان',36.805,2.92,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (23,'Raïs Hamidou','رايس حميدو',36.82,2.9,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (24,'Zéralda','زرالدة',36.72,2.83,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (25,'Mahelma','المحالمة',36.7,2.86,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (26,'Tessala El Merdja','تسالة المرجة',36.68,2.91,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (27,'Saoula','السوالة',36.69,2.98,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (28,'Staoueli','سطاوالي',36.75,2.87,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (29,'Ouled Fayet','أولاد فايت',36.72,2.91,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (30,'Draria','الدرارية',36.705,3.01,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (31,'Baba Hassan','بابا حسن',36.68,3.01,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (32,'Ouled Chebel','أولاد الشبل',36.67,3.05,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (33,'Khraïcia','الخرايسية',36.665,3.08,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (34,'Birtouta','بئر توتة',36.69,2.97,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (35,'El Harrach','الحراش',36.7167,3.1333,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (36,'Kouba','القبة',36.7267,3.0983,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (37,'Bachdjarah','باش جراح',36.71,3.12,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (38,'Bourouba','بوروبة',36.72,3.11,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (39,'Mohammadia','المحمدية',36.73,3.14,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (40,'Séhaoula','السحاولة',36.705,3.065,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (41,'Djasr Kasentina','جسر قسنطينة',36.735,3.155,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (42,'Gué de Constantine','جسر قسنطينة',36.725,3.17,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (43,'Baraki','براقي',36.67,3.1,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (44,'Les Eucalyptus','الكاليتوس',36.68,3.15,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (45,'Sidi Moussa','سيدي موسى',36.66,3.17,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (46,'Bab Ezzouar','باب الزوار',36.72,3.183,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (47,'Bordj El Bahri','برج البحري',36.74,3.21,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (48,'El Magharia','المغارية',36.71,3.165,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (49,'Oued Smar','واد السمار',36.71,3.145,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (50,'Dar El Beïda','الدار البيضاء',36.72,3.215,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (51,'Aïn Taya','عين الطاية',36.79,3.31,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (52,'Hraoua','الحراش',36.72,3.27,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (53,'Bordj El Kiffan','برج الكيفان',36.75,3.22,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (54,'Rouïba','الرويبة',36.73,3.285,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (55,'Reghaïa','الرغاية',36.725,3.345,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (56,'Douéra','الدويرة',36.668,2.948,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO commune (id,nom,nom_ar,centre_lat,centre_lng,circonscription) VALUES (57,'El Marsa','المرسى',36.805,3.258,NULL) ON CONFLICT (id) DO NOTHING;